export enum ExpenseStatus {
  PENDING_APPROVAL = 'PENDING_APPROVAL',
  PENDING_ISSUE = 'PENDING_ISSUE',
  PENDING_PHOTO = 'PENDING_PHOTO',
  PENDING_CONFIRMATION = 'PENDING_CONFIRMATION',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED',
}
